// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMxHVQqCGaMJ-L5zXy1cP67kI5rhrlKsg',
    appId: '1:281983169706:web:9ad6bbf1a4687962c44cd3',
    messagingSenderId: '281983169706',
    projectId: 'suyo-prototype-bd29f',
    authDomain: 'suyo-prototype-bd29f.firebaseapp.com',
    storageBucket: 'suyo-prototype-bd29f.firebasestorage.app',
    measurementId: 'G-SY4G8QEDRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZDJ6RLFo-bi9Aq9AnXGy68VGd2Luf0us',
    appId: '1:281983169706:android:c8e9d1d6feff1857c44cd3',
    messagingSenderId: '281983169706',
    projectId: 'suyo-prototype-bd29f',
    storageBucket: 'suyo-prototype-bd29f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhHZ0VmmAn0bf7sqy9q9fUPTydTG3ABUU',
    appId: '1:281983169706:ios:a4baada28ccb42bac44cd3',
    messagingSenderId: '281983169706',
    projectId: 'suyo-prototype-bd29f',
    storageBucket: 'suyo-prototype-bd29f.firebasestorage.app',
    iosBundleId: 'com.example.suyoPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhHZ0VmmAn0bf7sqy9q9fUPTydTG3ABUU',
    appId: '1:281983169706:ios:a4baada28ccb42bac44cd3',
    messagingSenderId: '281983169706',
    projectId: 'suyo-prototype-bd29f',
    storageBucket: 'suyo-prototype-bd29f.firebasestorage.app',
    iosBundleId: 'com.example.suyoPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMxHVQqCGaMJ-L5zXy1cP67kI5rhrlKsg',
    appId: '1:281983169706:web:0b100a3926ce6da1c44cd3',
    messagingSenderId: '281983169706',
    projectId: 'suyo-prototype-bd29f',
    authDomain: 'suyo-prototype-bd29f.firebaseapp.com',
    storageBucket: 'suyo-prototype-bd29f.firebasestorage.app',
    measurementId: 'G-X1MKZKTR0S',
  );
}
